"""Markdown/JSON report rendering for audit facts."""

import json


def _severity_label(finding):
    return "PASS" if finding["passed"] else "FAIL"


def render_markdown(facts):
    lines = [
        "# SneppX Shield Audit Report",
        "",
        f"- Artifact: `{facts['model']}`",
        f"- Kind: {'directory' if facts['is_dir'] else 'file'}",
        f"- Files: {facts['file_count']}  ({_human(facts['total_bytes'])})",
        f"- Signature verified: **{facts['signature_verified']}**",
        "",
        f"## Compliance score: {facts['compliance_passed']}/{facts['compliance_total']} "
        f"({facts['compliance_rating']})",
        "",
        "| ID | Control | Frameworks | Status |",
        "|----|---------|------------|--------|",
    ]
    for f in facts["compliance_findings"]:
        frameworks = ", ".join(f["frameworks"])
        lines.append(f"| {f['id']} | {f['title']} | {frameworks} | {_severity_label(f)} |")
    lines += ["", "## SBOM (first 20 files)", "", "| Path | Bytes | SHA-256 |", "|------|-------|---------|"]
    for entry in facts["bom"]["files"][:20]:
        sha = entry["sha256"] or "(skipped)"
        lines.append(f"| {entry['path']} | {entry['size_bytes']} | {sha} |")
    if facts["signature_detail"].get("error"):
        lines += ["", f"## Signature detail", "", f"- {facts['signature_detail']['error']}"]
    lines += ["", "---", "Generated by `sneppx-shield audit` (SneppX org)."]
    return "\n".join(lines) + "\n"


def render_json(facts):
    return json.dumps(facts, indent=2)


def render(facts, fmt="markdown"):
    if fmt == "json":
        return render_json(facts)
    return render_markdown(facts)


def _human(num):
    units = ["B", "KB", "MB", "GB"]
    value = float(num)
    for unit in units:
        if value < 1024 or unit == units[-1]:
            return f"{value:.1f} {unit}"
        value /= 1024